services:
  web:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate && gunicorn ubongo.wsgi:application -b 0.0.0.0 -p 8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=tinyllama:latest
      - CONTENT_GENERATION_ENABLED=true
    depends_on:
      - db
      - ollama

  db:
    build: ./docker/postgres
    ports:
      - "5433:5432"
    volumes:
      - ubongo_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  redis:
    image: redis:6
    ports:
      - '6379:6379'

  celery_worker:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=tinyllama:latest
      - CONTENT_GENERATION_ENABLED=true
    command: celery -A ubongo worker --loglevel=info
    depends_on:
      - redis
      - ollama

  celery_beat:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=tinyllama:latest
      - CONTENT_GENERATION_ENABLED=true
    command: celery -A ubongo beat --loglevel=info
    depends_on:
      - redis
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ubongo_postgres_data:
  ollama_data: