services:
  web:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate && gunicorn ubongo.wsgi:application -b 0.0.0.0 -p 8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=tinyllama:latest
      - CONTENT_GENERATION_ENABLED=true
    depends_on:
      - db
      - ollama

  db:
    build: ./docker/postgres
    ports:
      - "5433:5432"
    volumes:
      - ubongo_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  redis:
    image: redis:6
    ports:
      - '6379:6379'

  celery_worker:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=tinyllama:latest
      - CONTENT_GENERATION_ENABLED=true
    command: celery -A ubongo worker --loglevel=info
    depends_on:
      - redis
      - ollama

  celery_beat:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=tinyllama:latest
      - CONTENT_GENERATION_ENABLED=true
    command: celery -A ubongo beat --loglevel=info
    depends_on:
      - redis
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  n8n_db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${N8N_DB_USER}
      POSTGRES_PASSWORD: ${N8N_DB_PASSWORD}
      POSTGRES_DB: ${N8N_DB_NAME}
    volumes:
      - n8n_postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8n_db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${N8N_DB_NAME}
      - DB_POSTGRESDB_USER=${N8N_DB_USER}
      - DB_POSTGRESDB_PASSWORD=${N8N_DB_PASSWORD}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true

volumes:
  ubongo_postgres_data:
  ollama_data:
  n8n_postgres_data:

