# Generated by Django 5.2.4 on 2025-08-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articlepage_featured_articlepage_view_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
