# Generated by Django 5.2.4 on 2025-08-14 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articlepage_meta_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentGenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Topic for content generation', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('review', 'Ready for Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('prompt_used', models.TextField(blank=True)),
                ('generated_outline', models.TextField(blank=True)),
                ('generated_content', models.TextField(blank=True)),
                ('generated_title', models.CharField(blank=True, max_length=200)),
                ('generated_meta_description', models.CharField(blank=True, max_length=160)),
                ('generated_tags', models.TextField(blank=True, help_text='Comma-separated tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation_started_at', models.DateTimeField(blank=True, null=True)),
                ('generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('generation_time_seconds', models.IntegerField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('published_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.articlepage')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Generation Request',
                'verbose_name_plural': 'Content Generation Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIContentMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_generation_time', models.IntegerField(help_text='Total time in seconds')),
                ('outline_generation_time', models.IntegerField(blank=True, null=True)),
                ('content_generation_time', models.IntegerField(blank=True, null=True)),
                ('original_word_count', models.IntegerField()),
                ('final_word_count', models.IntegerField()),
                ('human_edit_percentage', models.FloatField(blank=True, help_text='Percentage of content that was human-edited', null=True)),
                ('avg_reading_time', models.FloatField(blank=True, null=True)),
                ('bounce_rate', models.FloatField(blank=True, null=True)),
                ('engagement_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_metrics', to='blog.articlepage')),
                ('generation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.contentgenerationrequest')),
            ],
            options={
                'verbose_name': 'AI Content Metrics',
                'verbose_name_plural': 'AI Content Metrics',
            },
        ),
    ]
