# Generated by Django 5.2.5 on 2025-08-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_add_web_scraping_models'),
    ]

    operations = [
    ]
