# Generated by Django 5.2.5 on 2025-08-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20250815_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='price',
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='bulk_pricing_tiers',
            field=models.JSONField(default=list, help_text='List of quantity-price tiers'),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='certifications',
            field=models.JSONField(default=list, help_text='CE, ISO, FDA, etc.'),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='color_options',
            field=models.JSONField(default=list, help_text='Available colors'),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='common_complaints',
            field=models.JSONField(default=list, help_text='Frequent issues mentioned'),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Size, weight, etc.', max_length=200),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='lead_time_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='material',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='minimum_order_quantity',
            field=models.IntegerField(blank=True, help_text='MOQ', null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='order_units',
            field=models.CharField(blank=True, help_text='pieces, kg, meters, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='port_of_shipment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='price_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='price_trend',
            field=models.CharField(blank=True, help_text='Rising/Falling/Stable', max_length=20),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='product_features',
            field=models.JSONField(default=list, help_text='Key features listed'),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='quality_standards',
            field=models.JSONField(default=list, help_text='Standards compliance'),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='rating_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='recent_orders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='response_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='review_highlights',
            field=models.JSONField(default=list, help_text='Key review points'),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='search_keywords',
            field=models.JSONField(default=list, help_text='SEO keywords from listing'),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='seasonal_demand',
            field=models.CharField(blank=True, help_text='High/Low season', max_length=100),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='shipping_methods',
            field=models.JSONField(default=list, help_text='Air, sea, express, etc.'),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='supplier_certifications',
            field=models.JSONField(default=list, help_text='ISO9001, etc.'),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='supplier_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='supplier_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='supplier_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='supplier_region',
            field=models.CharField(blank=True, help_text='Asia, Europe, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='trending_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='verification_status',
            field=models.CharField(blank=True, help_text='Gold, Verified, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='video_urls',
            field=models.JSONField(default=list, help_text='Product video URLs'),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='years_in_business',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='image_urls',
            field=models.JSONField(default=list, help_text='Product image URLs'),
        ),
    ]
