# Generated by Django 5.2.4 on 2025-08-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_scrapeddata_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('volume', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
