# Generated by Django 5.2.4 on 2025-08-14 00:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content_sections',
            field=wagtail.fields.StreamField([('featured_article', 2), ('latest_articles', 5), ('popular_articles', 8), ('ad_space', 15), ('category_highlight', 18), ('newsletter_signup', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Featured Article', 'max_length': 100}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('show_title', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Latest Articles', 'max_length': 100}), 4: ('wagtail.blocks.IntegerBlock', (), {'default': 6, 'help_text': 'Number of articles to display', 'max_value': 12, 'min_value': 1}), 5: ('wagtail.blocks.StructBlock', [[('title', 3), ('show_title', 1), ('number_of_articles', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Popular Articles', 'max_length': 100}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('week', 'This Week'), ('month', 'This Month'), ('all', 'All Time')], 'help_text': 'Time period for popularity calculation'}), 8: ('wagtail.blocks.StructBlock', [[('title', 6), ('show_title', 1), ('number_of_articles', 4), ('time_period', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Advertisement', 'max_length': 100, 'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('banner', 'Banner Ad'), ('square', 'Square Ad'), ('sidebar', 'Sidebar Ad'), ('custom', 'Custom HTML')]}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload ad image', 'required': False}), 12: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL when ad is clicked', 'required': False}), 13: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': "Custom HTML for ad (use only if ad_type is 'custom')", 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alt text for ad image', 'max_length': 200, 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('title', 9), ('ad_type', 10), ('ad_image', 11), ('ad_url', 12), ('ad_html', 13), ('alt_text', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Explore Categories', 'max_length': 100}), 17: ('wagtail.blocks.IntegerBlock', (), {'default': 6, 'help_text': 'Number of categories to display', 'max_value': 8, 'min_value': 3}), 18: ('wagtail.blocks.StructBlock', [[('title', 16), ('show_title', 1), ('number_of_categories', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'Stay Updated', 'max_length': 100}), 20: ('wagtail.blocks.CharBlock', (), {'default': 'Get the latest articles delivered to your inbox', 'max_length': 200, 'required': False}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary Blue'), ('secondary', 'Secondary Green'), ('gray', 'Gray'), ('dark', 'Dark')]}), 22: ('wagtail.blocks.StructBlock', [[('title', 19), ('subtitle', 20), ('background_color', 21)]], {})}),
        ),
    ]
